
runtime: python38
env: standard
instance_class: B1
handlers:
  - url: .*
    script: auto
env_variables:
  PROJECT_ID: practice-springml
  BUCKET: practice-springml.appspot.com
  PATH_TO_ASSET: side_input.json
basic_scaling:
  max_instances: 3
  idle_timeout: 5m
network: {}
service_account: practice-springml@appspot.gserviceaccount.com
service: default
# entrypoint: gunicorn -b :8080 -w 1 Bnb19AppAPI:app
entrypoint: gunicorn -b :8080 -w 1 main:app
default_expiration: "7d 7h"
vpc_access_connector:
  name: "projects/practice-springml/locations/us-central1/connectors/bnb19-app-api-connector"
  egress_setting: all-traffic
# inbound_services:
# - warmup