runtime: python38
env: standard
instance_class: B1
handlers:
  - url: .*
    script: auto
env_variables:
  PROJECT_ID: practice-springml
  BUCKET: practice-springml.appspot.com
  QUERY: tesla OR TSLA
basic_scaling:
  max_instances: 3
  idle_timeout: 5m
network: {}
service_account: practice-springml@appspot.gserviceaccount.com

entrypoint: gunicorn -b :$PORT -w 1 main:app
