
runtime: python38
env: standard
instance_class: B1
handlers:
  - url: .*
    script: auto
env_variables:
  PROJECT_ID: practice-springml-east
  BUCKET: practice-springml-east.appspot.com
  QUERY: tesla OR TSLA
basic_scaling:
  max_instances: 3
  idle_timeout: 5m

network: {}
# vpc_access_connector:
#   name: "projects/practice-springml-east/locations/us-east1/connectors/east-serverless-connector"
#   egress_setting: all-traffic
service_account: practice-springml-east@appspot.gserviceaccount.com

entrypoint: gunicorn -b :$PORT -w 1 main:app
inbound_services:
- warmup